### ISSUE TITLE
Shake in completion block of another shake

### ISSUE THREAD

**Issue by sochalewski** [andreamazz/UIView-Shake#11]
Is it even possible? I tried this and it works, but shake inside the completion handler looks like it has smaller delta than given. It barely shakes vertical.

```swift
view.subviews.forEach {
    $0.shake(5, withDelta: 50.0, speed: 1.0, shakeDirection: .Horizontal, completion: { 
        self.view.subviews.forEach {
            $0.shake(5, withDelta: 50.0, speed: 1.0, shakeDirection: .Vertical, completion: nil)
        }
    })
}
```

**Comment by andreamazz** [comment]
Hi @sochalewski 
Consider that you are applying the vertical shake several times to all the views.
If you have 5 views the completion is called 5 times. Each times you are going to apply the shake to the 5 views, so you'll end up with 5 shakes per view instead of 1. The shake appears to be subtle because there are 5 animations fighting each other.
Try like this:
```swift
view.subviews.forEach { view in
    view.shake(5, withDelta: 50.0, speed: 1.0, shakeDirection: .Horizontal, completion: { 
        view.shake(5, withDelta: 50.0, speed: 1.0, shakeDirection: .Vertical, completion: nil)
    })
}
```

**Comment by sochalewski** [comment]
You're completely right! This solution works perfect. Thank you so much 👍
